name: Cross-Platform Test
on: [push, pull_request]
jobs:
  test-linux:
    uses: ./.github/workflows/test-steps.yml
    with:
      os: ubuntu-latest
      test-command: sudo npm run test:nix
  test-macos:
    uses: ./.github/workflows/test-steps.yml
    with:
      os: macos-latest
      test-command: npm run test:mac
  test-windows:
    uses: ./.github/workflows/test-steps.yml
    with:
      os: windows-latest
      test-command: npm run test:win

  publish:
    needs: [test-linux, test-macos, test-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Set Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Install dependencies
      run: npm ci
    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
