name: Cross-Platform Test

# This specifies when the action should run.
on: [push, pull_request]

jobs:
  test:
    # This starts the matrix strategy.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        node-version: [14.x, 20.x]
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Sets up Node.js using a version from the matrix
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Installs dependencies
    - name: Install dependencies
      run: npm install

    # Runs your test script
    - name: Run tests
      run: npm run test:ci

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Set Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Install dependencies
      run: npm ci
    - name: Calculate version
      id: calc_version
      run: bash ci/getVersion.sh
    - name: Update version
      run: npm version ${{ steps.calc_version.outputs.VERSION }}

    # - name: Publish
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
